(def DEFAULT-CHAN-LIMIT 65536)

(def DEFAULT-CONFIG-FILE-NAME "jwno-config.janet")

(def DEFAULT-TOOLTIP-TIMEOUT 5000)
(def DEFAULT-CURRENT-FRAME-TOOLTIP-TIMEOUT 1000)
(def DEFAULT-KEYMAP-TOOLTIP-TIMEOUT 0)

(def TOOLTIP-MAX-WIDTH 1000) # XXX: Arbitrary value

(def DISPLAY-CHANGE-DELAY-TIME 3000)
