(def DEFAULT-CHAN-LIMIT 65536)

(def DEFAULT-CONFIG-FILE-NAME "jwno-config.janet")

(def DEFAULT-REPL-HOST "127.0.0.1")
(def DEFAULT-REPL-PORT 9999)

(def DEFAULT-REPL-EVAL-CLIENT-NAME "jwno-repl-eval")

(def DEFAULT-TOOLTIP-TIMEOUT 5000)
(def DEFAULT-CURRENT-FRAME-TOOLTIP-TIMEOUT 1000)
(def DEFAULT-KEYMAP-TOOLTIP-TIMEOUT 0)

(def DEFAULT-TOOLTIP-ANCHOR :top-left)
(def DEFAULT-CURRENT-FRAME-TOOLTIP-ANCHOR :center)

(def DEFAULT-TOOLTIP-MAX-WIDTH 1000) # XXX: Arbitrary value

(def DISPLAY-CHANGE-DELAY-TIME 2000)

(def USER-DEFAULT-SCREEN-DPI 96)

(def DEFAULT-FRAME-TREE-DUMP-INDENT-WIDTH 2)
(def DEFAULT-FRAME-TREE-DUMP-INDENT-CHAR 32)

(def KEYMAP-COMMAND-DESC-MAX-LENGTH 100) # XXX: Arbitrary value

(def GLOBAL-NAMESPACE-PREFIX "jwno/")

(def MESSAGE-WINDOW-CLASS "JwnoMsgWinClass")
(def MESSAGE-WINDOW-NAME  "Jwno Message Window")
