(def DEFAULT-CHAN-LIMIT 65536)

(def DEFAULT-CONFIG-FILE-NAME "jwno-config.janet")

(def DEFAULT-GENERIC-TOOLTIP-TIMEOUT 5000)
(def DEFAULT-CURRENT-FRAME-TOOLTIP-TIMEOUT 1000)

(def DISPLAY-CHANGE-DELAY-TIME 3000)
